export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const FETCH_PRODUCTS_LOADING = 'FETCH_PRODUCTS_LOADING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';

export const FETCH_BAG_SUCCESS = 'FETCH_BAG_SUCCESS';
export const GET_BAG_SUCCESS = 'GET_BAG_SUCCESS';

export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';